### ISSUE TITLE
Aufgabe 3 Probleme

### ISSUE THREAD

**Issue by Plagiatus** [LaurinBu/GIS-SoSe-2020#2]
Ampelwürdige Probleme:
- Mehrere Fehler in W3C.
- Das Menu sollte in die rechte obere Ecke, nicht die linke.
- Der Inhalt der Seite sollte nur 800 px breit sein, nicht die gesamte Seite überspannen.

Weitere Probleme:
- Die aktuelle Seite im Hauptmenü ist nur sehr schwer lesbar.

**Comment by LaurinBu** [comment]
Danke für das Feedback, habe gleich alles behoben!
Den Validator werde ich zukünftig auch mehr benutzen, hatte den nicht so im Blick.
