### ISSUE TITLE
Feedback A4

### ISSUE THREAD

**Issue by Plagiatus** [LaurinBu/GIS-SoSe-2020#3]
Ampelgründe: 
- brs sollten nicht mehr verwendet werden, jetzt wo ihr CSS benutzten könnt. Oder zumindest nicht um Abstand zu schaffen, verwende das BoxModell dafür.
- nur 3 von den 6 geforderten komplexen Selektoren.
- warum verschwindet der Einkaufswagen in der mittleren Größe?
- es sind immer 4 Artikel nebeneinander, selbst in der Mobilen Ansicht?

Weiteres
- Das Logo oben könnte eine Hintergrundfarbe haben.
- Umlaute in klassen/id namen sind suboptimal

**Comment by LaurinBu** [comment]
Hab alles überarbeitet, aber das die 4 Artikel nicht nebeneinander bleiben, sondern sich dann aufteilen, klappt irgendwie nicht :(
